theme: minima

title: Hello there
author: Nick Morozov
email: nmoro1ocdsb.ca
description: > # hey nice to meet you
  this is a very nice blog


# social links
twitter_username: your-twitter-handle #nickmorozov
github_username:  your-github-handle # NickMorozov13

show_excerpts: true # set to false to remove excerpts on the homepage
